### PR TITLE
Added robust standard errors

### PR DESCRIPTION
**Pull request by bjornerstedt**
Robust standard errors in OLS are important in econometrics, even at the introductory level. Here is a basic implementation for radiant.model::regress. 

/Jonas

### CODE REVIEW

**Comment by vnijs** [comment]
Thanks @bjornerstedt! I'll review soon and make sure this feature is added. Is there a particular reason you want to use HC1. I use HC0 for radiant.model::logistic

**Comment by bjornerstedt** [comment]
Nothing big: I am currently using Stata in my teaching, and it has HC1 as
default in robust estimation.

/Jonas

2017-05-19 23:58 GMT+02:00 Vincent Nijs <notifications@github.com>:

**Comment by vnijs** [comment]
I added robust estimation to the github repo using HC1 (incl. coefficient confidence intervals for Summary and Coefficient plot). Initial testing looks good but would appreciate your reaction. Install using:

```r
devtools::install_github("radiant-rstats/radiant.data")
devtools::install_github("radiant-rstats/radiant.basics")
devtools::install_github("radiant-rstats/radiant.model")
```

**Comment by vnijs** [comment]
You can get the latest version of radiant.model with the "robust" option for linear and logistic regression by using `radiant::update_radiant()`. Like I said, initial testing looks good but would appreciate your reaction

**Comment by vnijs** [comment]
@bjornerstedt I'll close this now. If you have any issues with the current implementation please do let me know.

**Pull request closed without merging**
